name: Build and Run

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Installing SUDO
      run: |
        sudo apt-get update && sudo apt-get install -y sudo && sudo rm -rf /var/lib/apt/lists/*
    
    - name: Installing GCC
      run: |
        sudo apt-get update && sudo apt-get install -y gcc g++
        
    - name: Install cppcheck
      run: |
        sudo apt-get update && sudo apt-get install -y cppcheck
    
    - name: Install pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        sudo ln -s /usr/bin/python3 /usr/bin/python
        sudo ln -s /usr/bin/pip3 /usr/bin/pip

    - name: Install lizard
      run: |
        pip install lizard
    
    - name: Create Build Files
      run: |
        make
    
    - name: Static Analysis
      run: |
        cppcheck --enable=all --error-exitcode=1 .
    
    - name: Cyclomatic Complexity Check
      run: |
        lizard --CCN 3
    
    - name: Unit test
      run: |
        ./testcheck
